"""add stock and warehouse tables

Revision ID: 0ffb5f0b4cdf
Revises: 53eb7031c5b5
Create Date: 2026-05-20 16:52:27.966173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffb5f0b4cdf'
down_revision: Union[str, Sequence[str], None] = '53eb7031c5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
